ECN3 v2023
ShipSoft/FairShip pull request #420
Opened 2023-03-09 17:44 UTC by olantwin

Changes needed for the new ECN3 geometry.

See here for dimensions of old geometry:
https://indico.cern.ch/event/1138547/contributions/4777211/attachments/2416232/4134679/2022_03_28_SHiP_LLO_study.pdf

And here for new dimensions:
https://indico.cern.ch/event/1138547/contributions/4777211/attachments/2416232/4134679/2022_03_28_SHiP_LLO_study.pdf

Rescaling:
- [ ] TimeDet
- [ ] UBT

2023-03-09 20:38 UTC, olantwin commented
@matclim, could you please check whether the scaling of the SplitCal looks sensible?
Do you happen to know whether the hcal geometry file is still used, or is that change superflous?

2023-03-09 21:00 UTC, olantwin commented
@antonioiuliano2 I did not adjust anything for the SND. I won't touch it so that you can do whatever you like.

2023-03-09 21:31 UTC, olantwin commented
![image](https://user-images.githubusercontent.com/3578823/224164013-f3323db4-890e-447f-b209-19595e8b25cc.png)
![image](https://user-images.githubusercontent.com/3578823/224164220-20948aee-9f00-4306-b62b-620f12727be5.png)

Clearly the naive scaling was only partially successful.

It seems the calorimeters and magnet in particular need more work, but it seems everything else also slightly collides with the floor. Maybe an issue with the beamline height?

2023-03-09 21:46 UTC, olantwin commented
![image](https://user-images.githubusercontent.com/3578823/224167313-34ed2381-6993-4507-828c-6b616c80218a.png)

Despite beam adjustment, there are conflicts with the cavern.

2023-03-09 22:00 UTC, matclim commented
@olantwin the actual Splitcal layout would vary depending on the used layer (horizontal or vertical) as a baseline option for 6x4m^2. It would be 4x6.12 m^2 for horizontal layers and 4.08x6m^2 for vertical layers.
![layout_std](https://user-images.githubusercontent.com/43775464/224168827-99b371d6-80d1-4447-bf12-1e3692da2f37.png)

I have myself have never used the hcal (as I'm focused on the SplitCal). In principle the SplitCal can also do hadronic calorimetry but you'd need extra layers, beyond the 20 X0 which are currently accounted for (a rough estimate implies ~15 times more lead than for just the eSplitCal). As such I think it's probably safe to just keep the hcal as it is for now.

2023-03-10 07:23 UTC, olantwin commented
@matclim Do you know whether the SplitCal should be in the simulation as the baseline? I just noticed that I have ECal and HCal in the render of the geometry.

2023-03-10 07:33 UTC, ThomasRuf commented
The problem with SplitCal, there is no reconstruction code for it. So, you can simulate it, but you will have no reco photons ore electrons to work with for reconstructing a signal.

2023-03-10 07:36 UTC, olantwin commented
Thanks for clarifying this, Thomas!

2023-03-10 07:42 UTC, ThomasRuf commented
In my mind, SplitCal still needs a proof of concept. It is an idea, but was never fully simulated, and the performances evaluated. This should be done outside of the default FairShip. For the moment, I think there is only the Shashlik calo option possible.

2023-03-15 11:35 UTC, olantwin commented
@leoredi pointed out that the second link was incorrect. This has been fixed.

2023-06-12 09:33 UTC, olantwin commented
Latest numbers from Richard

* UBT sensitive area: 1.20 x 2.90  (don't know what they have implemented as mechanics to hold the chambers but at least this makes the RPC overlap with the SBT
* Decay volume upstream (inner/outer): 1.00 x 2.70 / 1.40 x 3.10 (SBT thickness ~20cm)
* Decay volume downstream at 50m (inner/outer): 4.20 x 6.20 / 4.60 x 6.60 (SBT thickness ~20cm all  the way)
* Straw tracker sensitive area (all stations): 4.0 x 6.0 (don't know how much space mechanics takes in simulations)
* Ignore vacuum chamber through magnet
* Magnet 4x6m free aperture (inner/outer dimensions of yoke): 4.40 x 7.00 / 6.00 x 8.60 (the larger free vertical space around aperture is for coils)
* Timing detector sensitive area: 4.50 x 6.50 (don't know how much was reserved for mechanics in simulation)
* ECAL/MUON sensitiver area 5.00 x 6.50.

2023-06-17 08:42 UTC, antonioiuliano2 approved these changes
Thank you Oliver, it seems everything fine to me :)

2023-06-19 06:44 UTC, fairlyons requested changes
geometry_config.py
135:          c.Veto.sensitiveThickness = 0.2 * u.m
131 - 134: can probably be deleted
138:          c.Veto.rib = 1.5 * u.cm

veto.cxx
95:     f_RibThickness(1.5 * cm),
187:   double wx1 =  920 * mm;
188:   double wx2 = 4120 * mm;
197:   double wy1 = 2620 * mm;
198:   double wy2 = 6120 * mm;
829:   double ribThick = 15*mm;
lid thickness seems to be off still, I have not looked closely at this

2023-06-19 07:15 UTC, olantwin commented
> 131 - 134: can probably be deleted

I will probably make a massive PR soon to remove all the TP era code. Until then I'll leave this.

Implemented all of your other changes. Were these updated numbers from Andrea or did I make a mistake while importing your earlier changes?

For the lid, we can discuss at the ECN3 meeting. I think it would be good to have at least the correct material budget for the front face. For the back lid, it matters less.

2023-06-19 07:18 UTC, ThomasRuf commented
the back window also matters, the material will affect the EM performance.

2023-06-19 07:23 UTC, olantwin commented
> the back window also matters, the material will affect the EM performance.

While I generally agree, none of the studies which are going to be launched imminently use detectors after the back window. I'll raise the issue today at the meeting so that we can take a decision.

2023-06-19 07:46 UTC, fairlyons commented
> Implemented all of your other changes. Were these updated numbers from Andrea or did I make a mistake while importing your earlier changes?

These are new updates from Andrea, we had a clarifying discussion on Friday. He suggested to keep the outer dimensions as specified so the inner has to be reduced to account for wall thickness.

2023-06-19 08:34 UTC, olantwin commented
Action items from the ECN3 meeting:

- [ ] Check material budget
- [ ] Adjust thickness and material of entrance window
- [ ] Check material around the tracking stations

2023-06-26 08:50 UTC, olantwin commented
As discussed during today's ECN3 meeting, this is now ready for pilot productions. Merging.

2023-06-26 08:50 UTC, merged