Implement interim solution with SST parameters
ShipSoft/FairShip pull request #490
Opened 2024-08-23 13:46 UTC by ukmartylee

Retain plane setup for SST momentarily

Change stereoangle to double

2024-08-27 09:47 UTC, olantwin commented
Sorry, for the late reply. I somehow missed this.

I assume this fixes #489 ?

2024-08-27 09:49 UTC, olantwin requested changes
The changes look good.

Please test that there are no overlaps.

It would be good to squash these changes into a single commit and add a line to the changelog.

2024-08-29 05:40 UTC, anupama-reghunath approved these changes

2024-08-29 14:25 UTC, olantwin approved these changes

2024-08-29 14:26 UTC, merged