Remove all plane-related codes in SST
ShipSoft/FairShip pull request #552
Opened 2024-11-04 15:45 UTC by wcmartylee

Remove all plane-related codes due to implementation of compact (planeless) strawtubes configuration

2024-11-04 15:47 UTC, wcmartylee commented
#489

2024-11-05 10:10 UTC, olantwin commented
Thanks for this pull request!

Could you please prepare a presentation for Monday about these changes?

Some observations in no particular order:
* Currently there is a lot of hard-coding of detector IDs and conversions. We should probably have a set of functions to decode the ID instead of doing it by hand all over the place. (probably as part of the strawtubespoint/hit so that there is no desynchronisation between data and the way to decode the detector IDs)
* I don't like the multiple-return-by-reference style of the current decoding function. Would be nice to modernise this by e.g. returning a pair/tuple
* I assume this change will be very backwards incompatible, we should have a look how much breaks and whether there is a way to make the transition as simple as possible given reasonable effort
* The commit history is a mess
* At least the touched lines should be auto-formatted
* There is no need to modify the muflux files. I must have forgotten to remove them!

2024-11-05 15:01 UTC, wcmartylee commented
@olantwin 
Thanks for the review! Of course, I can give a presentation on the changes next Monday.

Some thoughts while I was midway of changing the detID: maybe it’s a lot easier and “safer” to leave the plane number 0 as it is. But either way, you’re right that we should have a separate function for construct and destruct. It was a pain in the ass to change them by hand.

And I’ll try to fix the commit history. (It was a learning-by-doing situation...)

2024-11-05 15:51 UTC, olantwin commented
> @olantwin Thanks for the review! Of course, I can give a presentation on the changes next Monday.

Great, I'll put you onto the agenda.

> Some thoughts while I was midway of changing the detID: maybe it’s a lot easier and “safer” to leave the plane number 0 as it is. But either way, you’re right that we should have a separate function for construct and destruct. It was a pain in the ass to change them by hand.

Maybe we can do two steps: move the detID encoding/decoding to a function and then in a second step change the detector ID calculation once, in a single spot while also incrementing the version of the strawtubespoint/hit
 
> And I’ll try to fix the commit history. (It was a learning-by-doing situation...)

No worries, 99% of what I know about git I learnt experimentally by repeatedly getting myself into trouble ;)

2024-11-15 14:07 UTC, olantwin commented
Could you please rebase to remove the merge conflicts? They result from deleted files which didn't need updating.

2024-11-15 14:08 UTC, wcmartylee commented
> Could you please rebase to remove the merge conflicts? They result from deleted files which didn't need updating.

Just did!

2024-11-15 14:13 UTC, olantwin commented
I think it might have been rebase the wrong way around, the [Remove last vestiges of muflux](https://github.com/ShipSoft/FairShip/pull/552/commits/6b9bde8cf19e9d7fe4cb8442bac092b233659ad8)
[6b9bde8](https://github.com/ShipSoft/FairShip/pull/552/commits/6b9bde8cf19e9d7fe4cb8442bac092b233659ad8) commit should precede your changes

2024-12-11 15:43 UTC, olantwin commented
@wcmartylee Any updates on this PR?

2024-12-12 09:36 UTC, wcmartylee commented
I’m sorry... I was busy with other things and couldn’t finish this fix. I was hoping we can complete this quickly on next week’s hackathon.

2024-12-12 10:24 UTC, olantwin commented
Indeed, for this kind of thing the hackathon should work well

2025-01-17 02:25 UTC, wcmartylee commented
@olantwin If this change doesn’t affect the pattern recognition, I can continue to work on it in February after I get back from holidays!

2025-01-17 12:28 UTC, olantwin commented
When would you be on your (well-deserved!) holiday? Is there anyone on the SST who I can contact in the meantime, in case I need information?

I think this pull request should not affect the broken pattern recognition for now, but if we fix it, we should make sure it's not broken by this PR again.

2025-01-21 08:32 UTC, wcmartylee commented
I’m currently on vacation till the end of the month. If needed, I think Daniel can answer some questions in my stead.

2025-02-13 13:10 UTC, olantwin commented
@wcmartylee Any updates?

2025-04-04 13:57 UTC, olantwin commented
@wcmartylee Any updates?

2025-05-14 11:52 UTC, olantwin commented
@wcmartylee My regular monthly question: Any updates?

2025-05-15 12:33 UTC, wcmartylee commented
> @wcmartylee My regular monthly question: Any updates?

Sorry for being so passive about this. I’ll devote some time into this and prepare a version to merge by next week the latest.

2025-05-15 15:40 UTC, olantwin commented
Thanks for the update

2025-05-22 08:11 UTC, olantwin commented
Seems that the update causes overlaps between different parts of the SST.

Any updates since last week?

2025-05-23 06:10 UTC, olantwin commented
Could you please remind everyone on Monday what these changes do exactly to the geometry?

Does the tracking performance change for the fake/real PR?

2025-05-23 12:44 UTC, wcmartylee commented
> Could you please remind everyone on Monday what these changes do exactly to the geometry?

Sure!

> Does the tracking performance change for the fake/real PR?

No significant changes can be observed.

2025-05-26 10:19 UTC, olantwin requested changes
Please (as discussed in today's meeting):

- [ ] Add a changelog entry
- [ ] Add methods to access view, straw etc.
- [ ] Revert the changes to the on-disk format of the hits and points
- [ ] Add checks to make sure we don't try to decode an old detector ID
- [ ] Consider removing/hiding the StrawDecode function, as it's probably not very useful for general users?

Nitpicks aside, this looks very good and I think we should be able to merge this any day now.

2025-05-26 10:25 UTC, olantwin commented
I'll also run clang-format over the changed lines later today.

2025-05-27 14:38 UTC, wcmartylee commented on geometry/geometry_config.py
> +    c.strawtubes.trydim = int(c.Yheight / 2.)
Just changed to station_height

2025-05-27 14:44 UTC, wcmartylee commented on strawtubes/strawtubes.h
> +    void StrawDecode(Int_t detID, int &statnb, int &vnb, int &lnb, int &snb);
Actually, the strawtubesHit and strawtubesPoint would still have to access this method for their own decoding.

2025-05-27 14:46 UTC, wcmartylee commented on strawtubes/strawtubesPoint.h
> +    Int_t statnb; /// station number
Removed

2025-05-27 15:05 UTC, olantwin requested changes
It's not ideal to use the navigator to do the check for a valid detector ID, as this means that it's not possible to decode the id without loading the geometry, and it could also be quite expensive.

2025-06-04 13:00 UTC, olantwin commented
Any updates?

2025-06-05 08:28 UTC, wcmartylee commented
> ```
> 2025-05-27@17:09:30:DEBUG:FairShip:FairShip:0: /__w/FairShip/FairShip/sw/SOURCES/FairShip/master/0/strawtubes/strawtubes.cxx: In member function 'std::tuple<int, int, int, int> strawtubes::StrawDecode(Int_t)':
> 2025-05-27@17:09:30:DEBUG:FairShip:FairShip:0: /__w/FairShip/FairShip/sw/SOURCES/FairShip/master/0/strawtubes/strawtubes.cxx:549:13: error: 'fDetectorID' was not declared in this scope; did you mean 'DetectorId'?
> 2025-05-27@17:09:30:DEBUG:FairShip:FairShip:0:   549 |     wire += fDetectorID + 1e3;
> 2025-05-27@17:09:30:DEBUG:FairShip:FairShip:0:       |             ^~~~~~~~~~~
> 2025-05-27@17:09:30:DEBUG:FairShip:FairShip:0:       |             DetectorId
> 2025-05-27@17:09:30:DEBUG:FairShip:FairShip:0: gmake[2]: *** [strawtubes/CMakeFiles/strawtubes.dir/build.make:92: strawtubes/CMakeFiles/strawtubes.dir/strawtubes.cxx.o] Error 1
> 2025-05-27@17:09:30:DEBUG:FairShip:FairShip:0: gmake[1]: *** [CMakeFiles/Makefile2:1412: strawtubes/CMakeFiles/strawtubes.dir/all] Error 2
> ```

Noted!

2025-06-05 08:30 UTC, wcmartylee commented on strawtubes/strawtubesHit.cxx
> +  strawtubes* module =
Other than accessing the `v_dirft` and `sigma_spatial`, which have to stay dynamic, `StrawDecode` and `StrawEndPoints` are now static.

2025-06-05 08:30 UTC, wcmartylee commented on python/shipPatRec.py
> +        is_stereo34 = ((decode[0] == 3) + (decode[0] == 4)) * ((decode[1] == 1) + (decode[1] == 2))
This works when I tested it.

2025-06-05 08:38 UTC, olantwin commented on strawtubes/strawtubesHit.cxx
> +  strawtubes* module =
What do you mean by static and dynamic here?

2025-06-05 08:43 UTC, wcmartylee commented on strawtubes/strawtubesHit.cxx
> +  strawtubes* module =
https://github.com/ShipSoft/FairShip/blob/47a307b0f33a7de580cd7873fab31fde3e7cfce7/strawtubes/strawtubes.h#L66-L67
This I’ve done, but not here:
https://github.com/ShipSoft/FairShip/blob/47a307b0f33a7de580cd7873fab31fde3e7cfce7/strawtubes/strawtubes.h#L136-L137

I tried set them to static but end up in these errors:
`cling::DynamicLibraryManager::loadLibrary(): /afs/cern.ch/user/w/welee/sw/slc9_x86-64/FairShip/master-local1/lib/libstrawtubes.so.0.0.0: undefined symbol: _ZN10strawtubes7v_driftE
Error in <TInterpreter::TCling::AutoLoad>: failure loading library strawtubes.so for strawtubes`

2025-06-05 08:44 UTC, olantwin commented on strawtubes/strawtubesHit.cxx
> +  strawtubes* module =
Why can't these be free functions (or constants for v_drift and sigma_spatial)?

2025-06-05 08:47 UTC, olantwin commented
pre-commit.ci autofix

2025-06-05 08:50 UTC, olantwin commented on strawtubes/strawtubesHit.cxx
> +  strawtubes* module =
See e.g. [here](https://stackoverflow.com/a/11852362)

2025-06-05 08:51 UTC, olantwin commented on strawtubes/strawtubesHit.cxx
> +  strawtubes* module =
v_drift and sigma_spatial IMO should be constants and not class members. Making them static class members makes no sense.

2025-06-06 07:59 UTC, wcmartylee commented on strawtubes/strawtubesHit.cxx
> +  strawtubes* module =
They are (for the moment) constant variables defined in geo config, and are set via Det_conf into strawtubes class as class members, which in turn are used in strawtubesHit for digitization. Until we have a better definition of these two variables, I would like to postpone this to a later pull request.

2025-06-06 09:09 UTC, olantwin commented on strawtubes/strawtubesHit.cxx
> +  strawtubes* module =
Why don't we define them directly in strawtubesHit.h as constants?
Then they can also be easily read from python.

But fine, we can postpone that change to a future pull request. Please make an issue to track it.

2025-06-06 09:12 UTC, olantwin commented on python/shipStrawTracking.py
> +            global_variables.modules["Strawtubes"].StrawDecode(hits['DetID'], statnb, vnb, lnb, snb)
Does this call need updating?

2025-06-10 12:15 UTC, wcmartylee commented on python/shipStrawTracking.py
> +            global_variables.modules["Strawtubes"].StrawDecode(hits['DetID'], statnb, vnb, lnb, snb)
Yes, I updated it. Thanks!

2025-06-11 09:52 UTC, olantwin approved these changes
Do you want to clean up the commit history or should I just squash everything into a single commit?

2025-06-11 13:12 UTC, olantwin commented on strawtubes/strawtubesHit.cxx
> +  strawtubes* module =
#756

2025-06-11 13:43 UTC, wcmartylee commented
> Do you want to clean up the commit history or should I just squash everything into a single commit?

Squash everything is fine. Thanks!

2025-06-11 15:54 UTC, merged