Make helium as the Decay volume medium default
ShipSoft/FairShip pull request #557
Opened 2024-11-11 16:09 UTC by anupama-reghunath

2024-11-12 10:08 UTC, olantwin requested changes

2024-11-12 10:08 UTC, olantwin commented on macro/run_simScript.py
> +parser.add_argument("--vacuums",dest="decayVolMed",help="Replace Decay Volume medium from helium to vacuum (vessel structure changes)",action="store_const",const="vacuums",default="helium")
It would be good to keep the `--helium` flag around for now as a NOOP, to not break the interface.

Could you please format this line sensibly?

2024-11-12 10:08 UTC, olantwin commented on macro/run_simScript.py
> +     DecayVolumeMedium=options.decayVolMed,
Good idea to change the name here!

2024-11-15 14:05 UTC, olantwin commented
Did you rebase the wrong way around?

2024-11-15 14:07 UTC, olantwin commented
Much better!

2024-11-15 14:09 UTC, anupama-reghunath commented
Yes! sometimes git commands confuse me. Will add the changes/comments needed in a bit.

2024-11-15 14:13 UTC, olantwin commented
Thanks!

2024-11-15 15:10 UTC, olantwin approved these changes
LGTM

2024-11-15 15:11 UTC, olantwin commented
Could you please add a line to the changelog?

2024-11-15 15:42 UTC, olantwin approved these changes

2024-11-18 10:49 UTC, merged