Added x-y-z coordinates for generating MuDIS
ShipSoft/FairShip pull request #561
Opened 2024-11-14 11:16 UTC by gzlatino

Added the option to specify the x, y and z coordinates of where the MuDIS interactions are generated

2024-11-15 08:29 UTC, olantwin requested changes
Generally looking good, mostly minor comments to clean things up a bit.

2024-11-15 08:29 UTC, olantwin commented on macro/run_simScript.py
> +parser.add_argument("--zRange", dest="mudis_z_range", nargs=2, help="lower and upper z limit of DIS interaction", required=False, default=[-999,999], type=float)
Might be worth having a look whether any other generators use a set range, in which case we can also use it there.
I don't like the default values, they should be something reasonable-ish.

The lines are too long.

The units expected should be mentioned.

2024-11-15 08:29 UTC, olantwin commented on macro/run_simScript.py
> + DISgen.SetPositions(options.mudis_z_range[0], options.mudis_z_range[1], options.mudis_x_range[0], options.mudis_x_range[1], options.mudis_y_range[0], options.mudis_y_range[1])
Very long line, can be simplified a bit by using the unpacking operator `*`

2024-11-15 08:29 UTC, olantwin commented on macro/run_simScript.py
> + print("MuDIS position nfo input:\nx_range =", options.mudis_x_range, "y_range =", options.mudis_y_range, "z_range = ", options.mudis_z_range)
Typo `nfo`, space missing after equals signs for `x_range` and `z_range`. Units would be useful.
Line very long.

2024-11-15 08:29 UTC, olantwin commented on shipgen/MuDISGenerator.cxx
> +    }
This should be at least `clang-format`ted, but could also benefit from some more explanatory comments and maybe clearer variable names.

2024-11-15 08:29 UTC, olantwin commented on shipgen/MuDISGenerator.cxx
> +         continue;
clang-format

2024-11-15 08:29 UTC, olantwin commented on shipgen/MuDISGenerator.h
> +  Double_t startZ, endZ, startX, endX, startY, endY;
One per line please

2024-11-15 08:29 UTC, olantwin commented on shipgen/MuDISGenerator.h
> +  ClassDef(MuDISGenerator,2);
missing space after comma

2024-12-11 15:43 UTC, olantwin commented
@gzlatino Any updates on this PR?

2025-01-16 09:15 UTC, olantwin commented
@gzlatino What's the status of this PR?

2025-01-16 09:45 UTC, gzlatino commented
@olantwin Working on it. Will update you soon.

2025-03-14 10:55 UTC, gzlatino commented
There's an error occurring when generating Muon DIS events with run_simScript.py using the --MuDIS option with or without specified coordinates. For every generated event I get this message:
```
++++  TG4Warning:  ++++
    TG4PrimaryGeneratorAction::CheckVMCStack:
    No primary particles found on the stack.
+++++++++++++++++++++++
```
After that the script finishes normally, but the newly created ROOT files are empty.

2025-03-14 14:09 UTC, anupama-reghunath commented
> No primary particles found on the stack.

I suspect that the inputfile used (`muonDis.root`) could be empty. How do you produce this?

2025-03-14 14:44 UTC, gzlatino commented
> > No primary particles found on the stack.
> 
> I suspect that the inputfile used (`muonDis.root`) could be empty. How do you produce this?

I am using the following command:

`python $FAIRSHIP/macro/run_simScript.py --MuDIS -f muonDis_1.root`

The result is the same no matter if I use the --xRange/yRange/zRange options.

The file is not empty. I downloaded it locally in case the issue was something to do with lxplus. Also tried running the same file in a branch where the changes from this PR aren't present and it works fine with the --MuDIS option.

2025-03-19 08:35 UTC, anupama-reghunath commented
MuonDIS simulation has some significant changes now in the master. Please rebase, and use the [makeMuonDIS.py](https://github.com/ShipSoft/FairShip/blob/master/muonDIS/makeMuonDIS.py) to generate a new DIS input file. 
Also useful: Submission scripts for [muonDIS simulations] (https://github.com/anupama-reghunath/HTCondor_scripts/tree/main/MuonDIS) Let me know if the issue still exists! :)

2025-04-04 13:56 UTC, olantwin commented
@gzlatino Any updates?

2025-04-18 13:05 UTC, olantwin commented
@gzlatino I'd appreciate an update on this at the next computing meeting (May 5).

2025-04-19 13:48 UTC, gzlatino commented
@olantwin I could give an update on May 5. I have rebased the branch and have resolved the conflicts that have arisen in the process. I just need good muon DIS files for testing. I already generated a bunch of files for the SBT and Tr case, as per Anupama's instructions, but the files are not good (I tried using them for MuDIS in a separate, clean branch and I get the same errors as when I am using them on this branch). Right now, I am in the process of generating new muon DIS files, starting by generating my own muon background files to test the changes in the branch, but if there are any good muon DIS files, that I can use for testing, they could speed up the process.

2025-04-19 16:18 UTC, anupama-reghunath commented
@gzlatino You can find muonDIS simulations (1 spill ) here : `/eos/experiment/ship/simulation/bkg/MuonDIS_2024helium`

2025-04-19 17:35 UTC, gzlatino commented
@anupama-reghunath Thanks for the info! There seems to be a mismatch between the ROOT version, used in my branch (6.30.08) and the ROOT version, with which the muonDIS files have been created (6.28.12), causing a whole cascade of problems and errors. I am still going to be looking into generating new muonDIS files for now.

2025-04-19 20:20 UTC, olantwin commented
> @anupama-reghunath Thanks for the info! There seems to be a mismatch between the ROOT version, used in my branch (6.30.08) and the ROOT version, with which the muonDIS files have been created (6.28.12), causing a whole cascade of problems and errors. I am still going to be looking into generating new muonDIS files for now.

Sorry, but two points: 
- the ROOT version is independent of the branch
- ROOT files are forwards compatible 

So this can't be the explanation. 

Could you please post the errors here?

2025-04-19 20:22 UTC, olantwin commented
> @olantwin I could give an update on May 5. 

Thanks!

> I have rebased the branch and have resolved the conflicts that have arisen in the process.

Could you please push the updated branch?

2025-04-19 20:23 UTC, olantwin commented
> @gzlatino You can find muonDIS simulations (1 spill ) here : `/eos/experiment/ship/simulation/bkg/MuonDIS_2024helium`

Thanks @anupama-reghunath !

2025-04-21 09:50 UTC, gzlatino commented
> Could you please push the updated branch?

I just pushed the updates.

> Sorry, but two points:
> 
> * the ROOT version is independent of the branch
> * ROOT files are forwards compatible
> 
> So this can't be the explanation.
> 
> Could you please post the errors here?

There are multiple lines in the output that look similar to this one:
```
TFile::Init:0: RuntimeWarning: no StreamerInfo found in /cvmfs/ship.cern.ch/24.10/sw/slc9_x86-64/GenFit/main-local1/lib/libgenfit2_rdict.pcm therefore preventing schema evolution when reading this file. The file was produced with version 6.28/12 of ROOT.
```
But I think you're right that this cannot be the explanation. I somehow missed the main error message last time. This is what I get at the end after trying to run the script:
```
Traceback (most recent call last):
  File "/afs/cern.ch/user/g/gzlatino/myFork_Fairship/sw/slc9_x86-64/FairShip/master-local1/macro/run_simScript.py", line 593, in <module>
    run.Run(options.nEvents)
cppyy.ll.SegmentationViolation: void FairRunSim::Run(int NEvents = 0, int NotUsed = 0) =>
    SegmentationViolation: segfault in C++; program state was reset
Exit normally
corrupted size vs. prev_size while consolidating
 *** Break *** abort
```

2025-04-21 10:09 UTC, olantwin commented
> > Could you please push the updated branch?
> 
> I just pushed the updates.
> 
> > Sorry, but two points:
> > 
> > * the ROOT version is independent of the branch
> > * ROOT files are forwards compatible
> > 
> > So this can't be the explanation.
> > Could you please post the errors here?
> 
> There are multiple lines in the output that look similar to this one:
> 
> ```
> TFile::Init:0: RuntimeWarning: no StreamerInfo found in /cvmfs/ship.cern.ch/24.10/sw/slc9_x86-64/GenFit/main-local1/lib/libgenfit2_rdict.pcm therefore preventing schema evolution when reading this file. The file was produced with version 6.28/12 of ROOT.
> ```
> 
> But I think you're right that this cannot be the explanation.

This is indeed unrelated. Still, please use the latest cvmfs release, if possible.

> I somehow missed the main error message last time. This is what I get at the end after trying to run the script:
> 
> ```
> Traceback (most recent call last):
>   File "/afs/cern.ch/user/g/gzlatino/myFork_Fairship/sw/slc9_x86-64/FairShip/master-local1/macro/run_simScript.py", line 593, in <module>
>     run.Run(options.nEvents)
> cppyy.ll.SegmentationViolation: void FairRunSim::Run(int NEvents = 0, int NotUsed = 0) =>
>     SegmentationViolation: segfault in C++; program state was reset
> Exit normally
> corrupted size vs. prev_size while consolidating
>  *** Break *** abort
> ```

This will need further investigation. Is there a stack-trace given by GDB?

2025-04-21 10:09 UTC, olantwin commented
BTW, your branch still has merge conflicts.

2025-04-21 10:58 UTC, gzlatino commented
> This is indeed unrelated. Still, please use the latest cvmfs release, if possible.
I am using the 25.01, which is the latest release as far as I can see.

> This will need further investigation. Is there a stack-trace given by GDB?
There is, but it is quite long and for the sake of continuity I've attached the whole output with the stack-trace:
[output.txt](https://github.com/user-attachments/files/19833117/output.txt)

> BTW, your branch still has merge conflicts.
Yes, I will resolve those.

Also, the code needs to be clang-formatted again, which I will do once everything else is working, of course.

2025-04-21 12:22 UTC, olantwin commented
Did you do a clean rebuild of FairShip after switching from 24.10 to 25.01?

2025-04-21 12:27 UTC, olantwin commented on shipgen/MuDISGenerator.cxx
> +        if (int(mu[0][0]) == int((*Part)[0])) {
Are you sure these elements always exist? That could potentially cause a segmentation violation.

2025-04-21 12:28 UTC, olantwin commented
The underlying issue seems to occur in `MuDISGenerator::ReadEvent()`

2025-04-21 12:49 UTC, gzlatino commented
> Did you do a clean rebuild of FairShip after switching from 24.10 to 25.01?

I believe so. I will do it again just in case something got I missed something in between rebasing,resolving the conflicts and all that.

> Are you sure these elements always exist? That could potentially cause a segmentation violation.
> The underlying issue seems to occur in `MuDISGenerator::ReadEvent()`

Will look more in depth into that.

2025-04-23 13:16 UTC, olantwin commented
> > Did you do a clean rebuild of FairShip after switching from 24.10 to 25.01?
> 
> I believe so.

Please do. So remove `sw/`, open a new shell and source the new release.

2025-04-25 12:29 UTC, gzlatino commented
@olantwin I have rebuilt the FairShip software, fixed the issues that came up and the segmentation fault is gone. But I'm back again in this situation:
```
++++  TG4Warning:  ++++
    TG4PrimaryGeneratorAction::CheckVMCStack:
    No primary particles found on the stack.
+++++++++++++++++++++++
```
Here is the whole [output](https://github.com/user-attachments/files/19907811/output.1.txt) again.

I am using the newly generated muonDIS.root files. Tried both with mine and the ones that Anupama suggested (/eos/experiment/ship/simulation/bkg/MuonDIS_2024helium). The result is the same. 

> Are you sure these elements always exist? That could potentially cause a segmentation violation.

I am currently looking into this, but this line was not added by me, so I am not sure whether it has something to do with the issues I am having.

2025-04-25 15:30 UTC, olantwin commented
I'm on holiday until the 5th.

2025-05-14 11:55 UTC, olantwin commented
Any updates on this? @gzlatino

2025-05-19 15:06 UTC, olantwin commented
Thanks for the update. While I can understand that resolving the conflicts might be non-trivial, at least resolve those that you committed please, as this is not in a state where it can be ran or tested.

Conflict annotations should never be committed.

2025-05-19 19:50 UTC, gzlatino commented
Sorry, about the lingering conflicts. I have resolved them. 

> Conflict annotations should never be committed.

I know, I must have done it by accident in previous commits. Will check more thoroughly going forward.

2025-05-19 20:27 UTC, olantwin commented
pre-commit.ci autofix

2025-05-19 20:28 UTC, olantwin commented
There are still some conflict annotations left over.

2025-05-20 13:22 UTC, olantwin commented on shipgen/MuDISGenerator.cxx
> +    // calculate start/end positions along this muon, and amout of material in between
typo

2025-05-20 13:22 UTC, olantwin commented on shipgen/MuDISGenerator.cxx
> +using std::endl;
Do you even use these?

2025-05-20 13:22 UTC, olantwin commented on macro/run_simScript.py
> +parser.add_argument("--zRange", dest="mudis_z_range", nargs=2, help="lower and upper z limit of DIS interaction", required=False, default=[-999,999], type=float)
Units are added, the other comments still apply.

2025-05-21 08:44 UTC, gzlatino commented on shipgen/MuDISGenerator.h
> +    const Double_t muon_mass = 0.10565999895334244;   // muon mass in GeV
You are correct, they are defined in the implementation file. I've removed them from this header.

2025-05-21 08:46 UTC, gzlatino commented on shipgen/MuDISGenerator.cxx
> +using std::endl;
They are not used. Removed as well. These lines, c_light and muon_mass in the header were not added by me originally. They were probably removed in previous commits and I must have reintroduced them accidentally while resolving some of my conflicts.

2025-05-21 13:48 UTC, olantwin commented on shipgen/MuDISGenerator.cxx
> +    }
Clang-format now done by me. Comments and variable names still appreciated.

2025-05-21 13:48 UTC, olantwin commented
Does this now run and produce the expected results?

2025-05-22 13:41 UTC, gzlatino commented on macro/run_simScript.py
> +parser.add_argument("--zRange", dest="mudis_z_range", nargs=2, help="lower and upper z limit of DIS interaction", required=False, default=[-999,999], type=float)
I'm sorry, I'm not sure I understand how to make the lines shorter. In the last update I separated them into multiple lines for readability, but I don't know if anything can be removed. Is the description too long? Also, for the default values, right now they are [-500, 500] for the x and y directions and [-4000, 4000] for the z direction, which is very roughly the size of the whole detector. By reasonable, do you mean a smaller volume or a specific place (like in front of the target maybe)?

2025-05-22 13:47 UTC, gzlatino commented
> Does this now run and produce the expected results?

It produces the results it did when I presented it in the software meeting a few weeks back.

2025-05-26 07:46 UTC, olantwin commented
Could you please upload your slides to that meeting agenda? If you make me look up an old meeting, please make sure the information is there.

I have a decent memory, but definitely not photographic. If you could remind me and anyone who might not have attended that particular meeting of the key results, that would be great.

2025-05-26 14:06 UTC, olantwin commented on macro/run_simScript.py
> +parser.add_argument("--zRange", dest="mudis_z_range", nargs=2, help="lower and upper z limit of DIS interaction", required=False, default=[-999,999], type=float)
> I'm sorry, I'm not sure I understand how to make the lines shorter. In the last update > I separated them into multiple lines for readability, but I don't know if anything can be removed. Is the description too long?

The description is fine, but could benefit from some language changes, e.g. "Lower and upper limits of x considered for muon DIS generator."

More importantly, `required` doesn't need to be specified, as it is false by default.
You also don't need to specify `dest`, as xyzRange would be used by default, and ideally we'd reuse these options for the other generators (at least GENIE).

And yes, line breaks would then take care of any remaining length issues.

> Also, for the default values, right now they are [-500, 500] for the x and y directions and [-4000, 4000] for the z direction, which is very roughly the size of the whole detector. By reasonable, do you mean a smaller volume or a specific place (like in front of the target maybe)?

You're right, I misread the number of zeros. Maybe use human-readable units here for the next person to look at the code? E.g. `-5*u.m, +5*u.m`

2025-05-28 10:53 UTC, gzlatino commented on macro/run_simScript.py
> +parser.add_argument("--zRange", dest="mudis_z_range", nargs=2, help="lower and upper z limit of DIS interaction", required=False, default=[-999,999], type=float)
The changes are done. Removed `required`; `dest` is changed to x/y/z_range since if I remove it completely the code does not work and the units are fixed.

2025-05-28 15:20 UTC, olantwin commented
OK, code-wise this looks good now.

Could you please confirm whether the physics results are as expected?
Your talk is unfortunately still not uploaded on the [indico](https://indico.cern.ch/event/1544285/).

2025-05-29 08:33 UTC, gzlatino commented
> OK, code-wise this looks good now.
> 
> Could you please confirm whether the physics results are as expected? Your talk is unfortunately still not uploaded on the [indico](https://indico.cern.ch/event/1544285/).

Sorry, I have forgotten to upload the slides. I uploaded then, although, there were no histograms on them. Could you please tell me what histograms I should get and I will send them.

2025-05-29 08:49 UTC, olantwin commented
It would be good to show histograms of the mu DIS vertex locations with/without this option enabled. A comparison of the performance with and without this change could also be useful.

2025-06-04 13:00 UTC, olantwin commented
Any updates?

2025-06-19 08:29 UTC, antonioiuliano2 commented
Personally, I am not currently using this PR.
> antonio

2025-06-26 16:03 UTC, olantwin commented
@gzlatino If you want this to be merged eventually, some initiative would be appreciated. For now I'll close this due to inactivity.

2025-06-26 16:03 UTC, closed without merging