correct default settings within geometry_config.py
ShipSoft/FairShip pull request #571
Opened 2024-11-28 16:03 UTC by anupama-reghunath

2024-11-28 16:08 UTC, olantwin commented
These defaults are for backwards compatibility, to allow e.g. reconstructing old files before helium and removal of the SND were options, so I don't think these need updating. 
Instead, we might consider throwing an error when trying to reconstruct these old files (and maybe give information this commit it was generated with, so that it can be reconstructed with the correct version).

2024-11-28 16:41 UTC, anupama-reghunath commented
atleast within the context of DecayVolume, the current version is not backwards compatible. 'vacuums' as default uses the current geometry for vacuum as opposed any  of the older geometries with 'vacuums'  as decayVolumeMedium.

2024-11-28 19:13 UTC, olantwin commented
Then at least for the DecayVolume we should probably just raise an error (with a helpful error message), instead of constructing an incompatible geometry.

2024-12-12 07:48 UTC, olantwin requested changes
Since we can still construct the SND, its default value for old geometries (which had an SND) should be True. @antonioiuliano2 what do you think?

Looks good to me otherwise.

2025-01-16 09:14 UTC, olantwin commented
@anupama-reghunath @antonioiuliano2 How shall we proceed with this PR?

2025-02-13 08:16 UTC, olantwin commented
Any updates? It would be nice to get this merged.

2025-03-05 09:11 UTC, olantwin commented
Closing because of lack of response.

2025-03-19 06:40 UTC, olantwin approved these changes

2025-03-19 06:40 UTC, merged

2025-03-19 06:44 UTC, olantwin commented
@anupama-reghunath Could you add a CHANGELOG entry for this? Dropping support for geometries without DecayVolumeMedium is worth making explicit there. The backward compatibility didn't actually exist, as even the vacuums case has changed relative to geometries without that variable.