new analysis_toolkit.py
ShipSoft/FairShip pull request #572
Opened 2024-11-28 22:38 UTC by anupama-reghunath

First version of a new toolkit script for analysis.
preselection_cut(show_table=True) returns a flag and produces a table for the candidate in the event.
Sample Output :

```
+----------------------------------+---------------------------+---------------------+-----------------------+
| Parameter                        | Value                     | Pre-selection cut   | Pre-selection Check   |
+==================================+===========================+=====================+=======================+
| Number of candidates in event    | 1                         | ==1                 | True                  |
+----------------------------------+---------------------------+---------------------+-----------------------+
| Time @ decay vertex (ns)         | 827.838314901504          |                     |                       |
+----------------------------------+---------------------------+---------------------+-----------------------+
| Impact Parameter (cm)            | 1.870657075982154         | IP < 250.0 cm       | True                  |
+----------------------------------+---------------------------+---------------------+-----------------------+
| DOCA (cm)                        | 0.1314989058928542        | DOCA < 1 cm         | True                  |
+----------------------------------+---------------------------+---------------------+-----------------------+
| Is within Fiducial Volume?       | True                      | True                | True                  |
+----------------------------------+---------------------------+---------------------+-----------------------+
| Dist2InnerWall (cm)              | 107.77691678708439        | > 5 cm              | True                  |
+----------------------------------+---------------------------+---------------------+-----------------------+
| Dist2VesselEntrance (cm)         | 4427.433487678709         | > 100 cm            | True                  |
+----------------------------------+---------------------------+---------------------+-----------------------+
| Invariant Mass (GeV)             | 0.9924035137310876        |                     |                       |
+----------------------------------+---------------------------+---------------------+-----------------------+
| Daughter Momentum [d1, d2] (GeV) | [10.6655147  17.80364632] | > 1 GeV             | True                  |
+----------------------------------+---------------------------+---------------------+-----------------------+
| Degrees of Freedom [d1, d2]      | [27 27]                   | > 25                | True                  |
+----------------------------------+---------------------------+---------------------+-----------------------+
| Reduced Chi^2 [d1, d2]           | [0.91172176 0.80305711]   | < 5                 | True                  |
+----------------------------------+---------------------------+---------------------+-----------------------+
| Pre-selection passed:            |                           |                     | True                  |
+----------------------------------+---------------------------+---------------------+-----------------------+

```
I've added an `analysis_example.py` in `macro/`, which was used for this output.

2024-11-29 19:26 UTC, olantwin commented
Thanks a lot for this! While I'm sure the details will evolve based on my (and hopefully others') feedback, I really appreciate the initiative!

Would you have time to briefly introduce the current implementation at the meeting Monday?

2024-11-29 21:09 UTC, anupama-reghunath commented
Yes, I do hope we can add on more as we go. I can briefly show the implementation on Monday's meeting :)

2024-12-03 10:49 UTC, olantwin commented
Maybe we could move the example to a new directly called `examples`.

@egamberini could we run the example in the CI?

2024-12-05 11:50 UTC, olantwin requested changes

2024-12-05 11:50 UTC, olantwin commented on macro/analysis_example.py
> +def Main_function():
```suggestion
def main():
```

Unless you give it a more descriptive name, the convention would be to call it `main`.

2024-12-05 11:50 UTC, olantwin commented on macro/analysis_example.py
> +Main_function()
```suggestion
if __name__ == "__main__":
    main()
```

2024-12-09 10:41 UTC, olantwin commented
One more general comment: 
For new python code, we should probably make a `ship` module, potentially with e.g. an `analysis_tools` submodule. For things that don't yet have a stable interface, we might initially want to hide them in an `experimental` namespace.

2024-12-18 08:00 UTC, olantwin approved these changes
I expect this to still undergo major changes, but merging this first version now, so that people can start using it and give feedback.

2024-12-18 08:01 UTC, olantwin commented
Oh, could you please add a line to the change log?

2024-12-18 08:24 UTC, olantwin approved these changes

2024-12-18 08:25 UTC, merged